name: Build CSET Installer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore CSETWebApi/CSETWeb_Api/CSETWeb_Api.sln

      - name: Build solution
        run: msbuild CSETWebApi/CSETWeb_Api/CSETWeb_Api.sln /p:Configuration=Release

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: CSET-installer
          path: installer/bin/Release/CSET-Installer.msi
